name: Build on GitHub

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # ────────────────────────────────────────────────
      # Source code & toolchains
      # ────────────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable-MSVC)
        uses: dtolnay/rust-toolchain@stable

      - name: Install full LLVM 16 with llvm-config (Chocolatey)
        shell: pwsh
        run: |
          choco install llvm --version=16.0.6 -y
          # Short 8.3 form of the path removes the space in "Program Files".
          $short = cmd /c "for %I in (\"$Env:ProgramFiles\\LLVM\") do @echo %~sI"
          $short = $short.Trim()
          Write-Host "LLVM short path = $short"
          # Export for later steps & llvm-sys build script
          "LLVM_SYS_160_PREFIX=$short" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          # Put bin dir on PATH for this and subsequent steps
          "$short\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

      # ────────────────────────────────────────────────
      # Sanity checks
      # ────────────────────────────────────────────────
      - name: Check tool versions
        shell: pwsh
        run: |
          rustc --version
          cargo --version
          llvm-config --version
          clang --version

      # ────────────────────────────────────────────────
      # Build & test
      # ────────────────────────────────────────────────
      - name: Show project manifest
        shell: pwsh
        run: |
          dir | select -First 20
          type Cargo.toml

      - name: Build project
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      # ────────────────────────────────────────────────
      # Artifacts
      # ────────────────────────────────────────────────
      - name: List built files
        shell: pwsh
        run: dir target\release

      - name: Upload executable(s)
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/release/*.exe
