name: Build on GitHub

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # ──────────────────────────────────────────────
      # Source & Rust toolchain
      # ──────────────────────────────────────────────
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      # ──────────────────────────────────────────────
      # Build LLVM 16 + cache (includes llvm-config)
      # ──────────────────────────────────────────────
      - name: Build LLVM 16 + cache
        uses: rush-lang/setup-llvm-action@v1
        with:
          llvm-version: "16.0.6"
          install-prefix: "C:/llvm16"   # no spaces
          projects: "clang;lld"
          targets: "X86"

      # ──────────────────────────────────────────────
      # Export env vars for llvm‑sys & PATH
      # ──────────────────────────────────────────────
      - name: Export LLVM env vars
        shell: pwsh
        run: |
          Write-Host "LLVM_PATH from action = $Env:LLVM_PATH"
          # llvm-sys expects this
          "LLVM_SYS_160_PREFIX=$Env:LLVM_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          # ensure llvm-config is on PATH
          "$Env:LLVM_PATH\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

      # ──────────────────────────────────────────────
      # Sanity checks
      # ──────────────────────────────────────────────
      - name: Tool versions & env
        shell: pwsh
        run: |
          rustc --version
          cargo --version
          Write-Host "LLVM_SYS_160_PREFIX = $Env:LLVM_SYS_160_PREFIX"
          llvm-config --version
          clang --version

      # ──────────────────────────────────────────────
      # Build & test
      # ──────────────────────────────────────────────
      - name: Cargo build
        run: cargo build --release --verbose

      - name: Cargo test
        run: cargo test --release --verbose

      # ──────────────────────────────────────────────
      # Artifacts
      # ──────────────────────────────────────────────
      - name: List release files
        shell: pwsh
        run: dir target\release

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/release/*.exe
