name: Build on GitHub

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # ────────────────────────────────────────────────
      # Source code & toolchains
      # ────────────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable-MSVC)
        uses: dtolnay/rust-toolchain@stable

      - name: Ensure clean LLVM 16 install in C:\llvm
        shell: pwsh
        run: |
          # Ako postoji neka druga verzija LLVM-a, ukloni je (ignoruje grešku ako nije instaliran)
          choco uninstall llvm -y || Write-Host "No previous LLVM to uninstall"

          # Instaliraj tačno 16.0.6 → folder bez razmaka
          choco install llvm --version=16.0.6 -y --allow-downgrade --force --params "'/InstallDir:C:\\llvm'"

          # Export za llvm-sys build.rs
          "LLVM_SYS_160_PREFIX=C:\\llvm" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

          # Dodaj bin u PATH za naredne korake
          "C:\\llvm\\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append

      # ────────────────────────────────────────────────
      # Sanity checks
      # ────────────────────────────────────────────────
      - name: Check tool versions & env
        shell: pwsh
        run: |
          rustc --version
          cargo --version
          Write-Host "LLVM_SYS_160_PREFIX = $Env:LLVM_SYS_160_PREFIX"
          llvm-config --version
          clang --version

      # ────────────────────────────────────────────────
      # Build & test
      # ────────────────────────────────────────────────
      - name: Show project manifest (first 20 entries)
        shell: pwsh
        run: |
          dir | select -First 20
          type Cargo.toml

      - name: Build project
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      # ────────────────────────────────────────────────
      # Artifacts
      # ────────────────────────────────────────────────
      - name: List built files
        shell: pwsh
        run: dir target\release

      - name: Upload executable(s)
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/release/*.exe
