name: Build on GitHub

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
        
    - name: Check Rust version
      run: |
        rustc --version
        cargo --version
        
    - name: Check project structure
      run: |
        dir
        type Cargo.toml
        
    - name: Build project
      run: cargo build --release --verbose
      
    - name: Run tests
      run: cargo test --release --verbose
      
    - name: List built files
      run: dir target\release
      
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: target/release/*.exe
