name: Build on GitHub

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Build project
      run: cargo build --release
      
    - name: Run tests
      run: cargo test --release
      
    - name: List built files
      run: dir target\release
      
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: target/release/*.exe
